### ISSUE TITLE
Add Issues templates

### ISSUE THREAD

**Issue by laysauchoa** [laysauchoa/opensearch-python-dive-in#4]
Repository is missing issue templates like questions, bugs, etc.

**Comment by rsk2** [comment]
Hi @laysauchoa, I am interested in working on this. Do you already have any specific templates in mind for the issue templates?

**Comment by laysauchoa** [comment]
You can work on this. I do not have a specific template in mind, bring your idea and we can go from there.

**Comment by rsk2** [comment]
Hi @laysauchoa, I have added templates and created a PR. Can you please take a look?
